
# Site Settings
title: Training by Serli
email: tanguy.desplebain@serli.com
description: Training by Serli . FORMATIONS & WORKSHOPS
baseurl: ""
url: "http://localhost:4000"
github_username:  Seikicegus
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', '_trainings']
kramdown:
  input: GFM
