
# Site Settings
title: Start Jekyll
email: tanguy.desplebain@serli.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/formation"
url: "http://Seikicegus.github.io"
github_username:  Seikicegus
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
