
# Site Settings
title: Start Jekyll
email: tanguy.desplebain@serli.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
github_username:  Seikicegus
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
